### PR TITLE
Base class docstrings major update

### PR DESCRIPTION
**Pull request by arekbulski**
I reviewed the docstrings in base class again, and fixed all major issues. Please accept it in entirety. We neeed to make documentation better. Ping @lurch 

Included closed issue https://github.com/PyFilesystem/pyfilesystem/issues/230 and previous patch https://github.com/PyFilesystem/pyfilesystem/pull/231

### CODE REVIEW

**Comment by arekbulski** [comment]
I am kinda green when it comes to pull requests. This was supposed to be a simple change and I ended up adding several commits...

**Comment by lurch** [comment]
(The reason you accidentally added extra commits to this PR, was because you've submitted a PR directly from you `master` branch, and so whenever you update your `master`, this PR will get updated too. The normal way of doing things on github to create a new branch (off master), make your changes to the branch, and then PR from there. And then you're free to carry on updating your master branch (as a 'clean copy' of upstream) with any work you do always done on separate branches.)

**Comment by lurch** [comment]
And I'll try to review this patch one evening this week, if I have time.

**Comment by arekbulski** [comment]
Reopening under dedicated branch. Thank you for guidance.

**Pull request closed without merging**
