### PR TITLE
Corrected several URLs to where they are after the code.google.com close

### PR DESCRIPTION
**Pull request by GadgetSteve**
I have left the URL for the discussion group alone as it is still available.

Addresses #366

### CODE REVIEW

**Comment by willmcgugan** [comment]
Good point. The checkout in the getting started should be `git clone`, rather than `svn checkout`.

**Comment by GadgetSteve** [comment]
Good point - While I am at it I guess I should change `hidefs.py` to default as hidden `".git"` as well as `".svn"`, *(for good measure I am tempted to throw in `.hg` as well)*, and replace `.svn` with `.git` in both `fs/tests/test_path.py` and `fs/tests/__init__.py`

**Comment by arekbulski** [comment]
@GadgetSteve You should replace the entire line, not just components of svn checkout.
`git clone https://github.com/PyFilesystem/pyfilesystem.git pyfilesystem-read-only`
should really be
`git clone https://github.com/PyFilesystem/pyfilesystem.git`
which is the git-way of doing it, but then the resulting folder is named differently.

**Comment by GadgetSteve** [comment]
I was going for the same naming of the resulting directory.

**Pull request closed without merging**
