### PR TITLE
rename README for GitHub to properly render it

### PR DESCRIPTION
**Pull request by hmeine**
After renaming README to have the .md extension, it will be properly rendered by GitHub on the main repository page.

In my opinion, the Wiki can then be disabled, so that there is only one information source / page to maintain.

### CODE REVIEW

**Comment by arekbulski** [comment]
You should change `MANIFEST.in` to refer to renamed readme file.

**Comment by hmeine** [comment]
Right, I also corrected ``setup.py`` now.

**Comment by arekbulski** [comment]
After this is accepted, the wiki page should be discarded. Just saying.

**Comment by lurch** [comment]
Thanks.

**Pull request merged**
