### PR TITLE
allow any s3fs connection args

### LINKED ISSUE #211: AWS Credentials for S3 shouldn't require environment variables
Boto supports multiple ways to provide AWS credentials (key and key_id) besides just as environment variables.  More info in [the boto docs](http://boto.readthedocs.org/en/latest/boto_config_tut.html#details).

But basically instead of requiring environment variables [see fs/s3fs.py] (https://github.com/PyFilesystem/pyfilesystem/blob/master/fs/s3fs.py#L112) we can let boto pull it from the ~/.aws/credentials file (supported by boto, boto3 and other AWS SDKs) or other standardized locations as well as from IAM roles (using ec2 instance metadata magic) when running on EC2 without having to hard-code credentials.

### PR DESCRIPTION
**Pull request by aisch**
so we can use boto to deduce all this from env rather than hardcoding.

should still work w/ previous calls except that: cxn failure due to missing creds is delayed to first `S3FS._s3conn`, if you like i can update pr to try cxn once in `S3FS.__init__` and convert missing creds error to `CreateFailedError` there.

closes #211

### CODE REVIEW

**Comment by aisch** [comment]
@lurch any interest in merging this pr?

**Comment by lurch** [comment]
I'm afraid I've never even looked at any of the S3FS code - that's more @willmcgugan 's or @rfk 's area.

**Comment by aisch** [comment]
@willmcgugan @rfk do these S3FS changes look ok to merge?

**Comment by jimbocoder** [comment]
We'd love to see this merged if there are no blockers!  Looks good to me, but I don't maintain this project :)

**Comment by lurch** [comment]
Well I've never used any S3 stuff, so I haven't tested this PR. And even though @willmcgugan or @rfk haven't provided any feedback, this change looks okay from a quick glance, so I'll go ahead and merge it anyway, and hope it doesn't break anything ;-)

**Comment by jimbocoder** [comment]
We've taken this all the way from dev through to production and it's working great for 3 days now without issue.

@lurch I'm curious about a practical aspect.  I notice this change is not in pypi even though it's present in the master branch here.  Is there some periodic update to pypi for this project, or a testing process that needs to happen first, or what?  Currently we've forked this repo, but usually vanilla pypi would be way nicer :)

Thanks for merging this!

**Comment by lurch** [comment]
Thanks for the positive feedback :+1: 

pypi releases are entirely managed by @willmcgugan (the creator and owner of this project), and out of my hands.

**Comment by aisch** [comment]
@jimbocoder @lurch thx for getting this merged :tada:

**Comment by jimbocoder** [comment]
@willmcgugan After a couple months now, we've put tens of millions of files through this change, with no adverse effects to report! Would love to see this one make it into the pypi index, so we can "unfork" the pypi release! Thanks!

**Pull request merged**
