### PR TITLE
Update fs.expose.ftp for compatibility with latest pyftpdlib.

### PR DESCRIPTION
**Pull request by travcunn**
The pyftpdlib project has moved some imports that will be problematic when a new release is created. This should be merged as soon as pyftpdlib creates a new release (newer than 1.4).

### CODE REVIEW

**Comment by willmcgugan** [comment]
I guess I should pin pyfilesystem to pyftpdlib 1.4?

**Comment by lurch** [comment]
@travcunn Could you please rework this PR so that it only contains commit 08bac4b and not the unrelated commits?
(Easiest method might be to close this PR, create a new branch, recreate your fixes there, and submit a PR from that branch?)

**Comment by kitsmag** [comment]
A `git rebase` plus `git push -f` [might work, too](https://stackoverflow.com/a/32818657/321973)

**Comment by kitsmag** [comment]
I took the liberty of re-requesting #217 without the unrelated parts as #239 (also, I put this account to rest and use my private one, @zommuter)

**Comment by lurch** [comment]
Closing in favour of #243

**Pull request closed without merging**
