### PR TITLE
Dokany 0.8.0

### PR DESCRIPTION
**Pull request by zommuter**
First attempt at Dokany 0.8.0 compatibility, still WIP

### CODE REVIEW

**Comment by zommuter** [comment]
Currently not working properly, see https://github.com/PyFilesystem/pyfilesystem/issues/236#issuecomment-169996346

**Comment by lurch** [comment]
Other thoughts:
  * I guess if Dokan is supporting arbitrary paths rather than just single drive-letters, maybe it's worth adding support for long path-names, similar to what [OSFS does](https://github.com/PyFilesystem/pyfilesystem/blob/master/fs/osfs/__init__.py#L105) ? (I guess the UNC stuff here isn't relevant to Dokan though). If that's something that Dokan DLL supports, of course ;)
  * I've not experimented with Dokan, but if mounting to a nested path (rather than just a non-existent drive-letter), does that path need to already exist (like mountpoints on Linux)? And if so, would it be worth checking for that first in the python-side code, or should it just let the error bubble back up from the Dokan DLL?

**Comment by zommuter** [comment]
Good questions... I know dokan can pretend to be a network drive as well, but UNC shouldn't matter; concerning nested paths I'd leave that to the DLL for now. The `mirror.exe` shipped with dokany does unfortunately still only work with drive letters it seems. Maybe the whole drive-path issue should be moved to a separate branch and getting dokany 0.8.0 to work at all should be prioritized on first...

**Comment by zommuter** [comment]
I moved the `drive` to `path` part to https://github.com/zommuter/pyfilesystem/tree/dokany-paths, unfortunately that seems to have deleted our comments on that...

**Comment by lurch** [comment]
Closing in favour of #256

**Pull request closed without merging**
